MiniGrid-Empty-Random-5x5-v0: &minigrid-defaults
  env_wrapper: minigrid.wrappers.FlatObsWrapper # See GH/1320#issuecomment-1421108191
  normalize: true
  n_envs: 8 # number of environment copies running in parallel
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  n_steps: 128 # batch size is n_steps * n_env
  batch_size: 64 # Number of training minibatches per update
  gae_lambda: 0.95 #  Factor for trade-off of bias vs variance for Generalized Advantage Estimator
  gamma: 0.99
  n_epochs: 10 #  Number of epoch when optimizing the surrogate
  ent_coef: 0.0 # Entropy coefficient for the loss caculation
  learning_rate: 2.5e-4 # The learning rate, it can be a function
  clip_range: 0.2 # Clipping parameter, it can be a function

MiniGrid-UnlockPickup-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-UnlockPickup-OracleDecomposedReward-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-UnlockPickup-OracleDecomposedReward-NoMission-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-UnlockPickup-OracleDecomposedReward-NoReward-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-UnlockPickup-OracleDecomposedReward-NoMission-NoReward-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-PutNext-6x6-N2-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-IsNextTo-6x6-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-IsNextTo-6x6-DecomposedReward-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-IsNextTo-6x6-DecomposedReward-NoMission-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-IsNextTo-6x6-DecomposedReward-NoReward-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-IsNextTo-6x6-DecomposedReward-NoMission-NoReward-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-IsNextTo-6x6-OracleDecomposedReward-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-IsNextTo-6x6-OracleDecomposedReward-NoMission-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-IsNextTo-6x6-OracleDecomposedReward-NoReward-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5

MiniGrid-IsNextTo-6x6-OracleDecomposedReward-NoMission-NoReward-v0: 
  <<: *minigrid-defaults
  n_timesteps: !!float 3e5
